import {
    DataExchangeColumn,
    ExportEntity,
    ImportEntity,
} from './data-exchange.entity';

export const exportColumns: Record<ExportEntity, DataExchangeColumn[]> = {
    patients: [
        { key: 'id', header: 'id' },
        { key: 'userId', header: 'userId' },
        { key: 'firstName', header: 'firstName' },
        { key: 'lastName', header: 'lastName' },
        { key: 'email', header: 'email' },
        { key: 'phone', header: 'phone' },
        { key: 'dateOfBirth', header: 'dateOfBirth' },
        { key: 'gender', header: 'gender' },
        { key: 'bloodType', header: 'bloodType' },
        { key: 'personalNumber', header: 'personalNumber' },
        { key: 'address', header: 'address' },
        { key: 'emergencyContact', header: 'emergencyContact' },
        { key: 'emergencyPhone', header: 'emergencyPhone' },
        { key: 'isActive', header: 'isActive' },
        { key: 'createdAt', header: 'createdAt' },
        { key: 'updatedAt', header: 'updatedAt' },
    ],
    appointments: [
        { key: 'id', header: 'id' },
        { key: 'patientId', header: 'patientId' },
        { key: 'patientName', header: 'patientName' },
        { key: 'departmentId', header: 'departmentId' },
        { key: 'departmentName', header: 'departmentName' },
        { key: 'serviceCatalogId', header: 'serviceCatalogId' },
        { key: 'serviceName', header: 'serviceName' },
        { key: 'staffProfileId', header: 'staffProfileId' },
        { key: 'staffLabel', header: 'staffLabel' },
        { key: 'status', header: 'status' },
        { key: 'appointmentType', header: 'appointmentType' },
        { key: 'scheduledAt', header: 'scheduledAt' },
        { key: 'endAt', header: 'endAt' },
        { key: 'durationMinutes', header: 'durationMinutes' },
        { key: 'basePrice', header: 'basePrice' },
        { key: 'createdAt', header: 'createdAt' },
    ],
    'lab-results': [
        { key: 'labOrderId', header: 'labOrderId' },
        { key: 'labOrderItemId', header: 'labOrderItemId' },
        { key: 'patientId', header: 'patientId' },
        { key: 'patientName', header: 'patientName' },
        { key: 'labTestId', header: 'labTestId' },
        { key: 'labTestCode', header: 'labTestCode' },
        { key: 'labTestName', header: 'labTestName' },
        { key: 'resultValue', header: 'resultValue' },
        { key: 'resultUnit', header: 'resultUnit' },
        { key: 'resultStatus', header: 'resultStatus' },
        { key: 'isCritical', header: 'isCritical' },
        { key: 'completedAt', header: 'completedAt' },
        { key: 'orderedAt', header: 'orderedAt' },
    ],
    'inventory-items': [
        { key: 'id', header: 'id' },
        { key: 'sku', header: 'sku' },
        { key: 'name', header: 'name' },
        { key: 'categoryId', header: 'categoryId' },
        { key: 'categoryName', header: 'categoryName' },
        { key: 'departmentId', header: 'departmentId' },
        { key: 'departmentName', header: 'departmentName' },
        { key: 'unitOfMeasure', header: 'unitOfMeasure' },
        { key: 'currentStock', header: 'currentStock' },
        { key: 'reorderLevel', header: 'reorderLevel' },
        { key: 'unitCost', header: 'unitCost' },
        { key: 'expiryDate', header: 'expiryDate' },
        { key: 'isActive', header: 'isActive' },
        { key: 'createdAt', header: 'createdAt' },
    ],
    billings: [
        { key: 'id', header: 'id' },
        { key: 'billingNumber', header: 'billingNumber' },
        { key: 'patientId', header: 'patientId' },
        { key: 'patientName', header: 'patientName' },
        { key: 'appointmentId', header: 'appointmentId' },
        { key: 'status', header: 'status' },
        { key: 'subtotal', header: 'subtotal' },
        { key: 'taxAmount', header: 'taxAmount' },
        { key: 'discountAmount', header: 'discountAmount' },
        { key: 'totalAmount', header: 'totalAmount' },
        { key: 'amountPaid', header: 'amountPaid' },
        { key: 'dueDate', header: 'dueDate' },
        { key: 'issuedAt', header: 'issuedAt' },
        { key: 'paidAt', header: 'paidAt' },
    ],
    'audit-logs': [
        { key: 'id', header: 'id' },
        { key: 'action', header: 'action' },
        { key: 'entityType', header: 'entityType' },
        { key: 'entityId', header: 'entityId' },
        { key: 'performedByUserId', header: 'performedByUserId' },
        { key: 'ipAddress', header: 'ipAddress' },
        { key: 'userAgent', header: 'userAgent' },
        { key: 'requestId', header: 'requestId' },
        { key: 'metadata', header: 'metadata' },
        { key: 'createdAt', header: 'createdAt' },
    ],
};

export const importTemplates: Record<
    ImportEntity,
    { columns: DataExchangeColumn[]; sample: Record<string, string> }
> = {
    patients: {
        columns: [
            { key: 'firstName', header: 'firstName' },
            { key: 'lastName', header: 'lastName' },
            { key: 'email', header: 'email' },
            { key: 'phone', header: 'phone' },
            { key: 'dateOfBirth', header: 'dateOfBirth' },
            { key: 'gender', header: 'gender' },
            { key: 'bloodType', header: 'bloodType' },
            { key: 'personalNumber', header: 'personalNumber' },
            { key: 'address', header: 'address' },
            { key: 'emergencyContact', header: 'emergencyContact' },
            { key: 'emergencyPhone', header: 'emergencyPhone' },
            { key: 'isActive', header: 'isActive' },
            { key: 'userId', header: 'userId' },
        ],
        sample: {
            firstName: 'Ada',
            lastName: 'Lovelace',
            email: 'ada@example.com',
            phone: '+38344111222',
            dateOfBirth: '1995-04-10',
            gender: 'female',
            bloodType: 'A_POSITIVE',
            personalNumber: '1234567890',
            address: 'Mother Teresa Blvd',
            emergencyContact: 'Family Contact',
            emergencyPhone: '+38344111333',
            isActive: 'true',
            userId: '',
        },
    },
    'inventory-items': {
        columns: [
            { key: 'sku', header: 'sku' },
            { key: 'name', header: 'name' },
            { key: 'inventoryCategoryId', header: 'inventoryCategoryId' },
            { key: 'categoryName', header: 'categoryName' },
            { key: 'departmentId', header: 'departmentId' },
            { key: 'departmentName', header: 'departmentName' },
            { key: 'description', header: 'description' },
            { key: 'unitOfMeasure', header: 'unitOfMeasure' },
            { key: 'currentStock', header: 'currentStock' },
            { key: 'reorderLevel', header: 'reorderLevel' },
            { key: 'unitCost', header: 'unitCost' },
            { key: 'expiryDate', header: 'expiryDate' },
            { key: 'isActive', header: 'isActive' },
        ],
        sample: {
            sku: 'INV-001',
            name: 'Surgical Gloves',
            inventoryCategoryId: '',
            categoryName: 'Medical Supplies',
            departmentId: '',
            departmentName: 'Surgery',
            description: 'Box of nitrile gloves',
            unitOfMeasure: 'box',
            currentStock: '100',
            reorderLevel: '20',
            unitCost: '12.50',
            expiryDate: '2027-01-31',
            isActive: 'true',
        },
    },
    'lab-tests': {
        columns: [
            { key: 'code', header: 'code' },
            { key: 'name', header: 'name' },
            { key: 'description', header: 'description' },
            { key: 'category', header: 'category' },
            { key: 'sampleType', header: 'sampleType' },
            { key: 'defaultPrice', header: 'defaultPrice' },
            { key: 'referenceRange', header: 'referenceRange' },
            { key: 'isActive', header: 'isActive' },
        ],
        sample: {
            code: 'CBC',
            name: 'Complete Blood Count',
            description: 'Standard blood panel',
            category: 'Hematology',
            sampleType: 'Blood',
            defaultPrice: '20.00',
            referenceRange: '4.0-10.0',
            isActive: 'true',
        },
    },
    'service-catalog': {
        columns: [
            { key: 'departmentId', header: 'departmentId' },
            { key: 'departmentName', header: 'departmentName' },
            { key: 'name', header: 'name' },
            { key: 'description', header: 'description' },
            { key: 'defaultDurationMinutes', header: 'defaultDurationMinutes' },
            { key: 'defaultPrice', header: 'defaultPrice' },
            { key: 'isActive', header: 'isActive' },
            { key: 'sortOrder', header: 'sortOrder' },
        ],
        sample: {
            departmentId: '',
            departmentName: 'Cardiology',
            name: 'Cardiology Consultation',
            description: 'Initial specialist consultation',
            defaultDurationMinutes: '30',
            defaultPrice: '40.00',
            isActive: 'true',
            sortOrder: '0',
        },
    },
    staff: {
        columns: [
            { key: 'userId', header: 'userId' },
            { key: 'staffPositionTypeId', header: 'staffPositionTypeId' },
            { key: 'staffPositionTypeName', header: 'staffPositionTypeName' },
            { key: 'employeeCode', header: 'employeeCode' },
            { key: 'specialization', header: 'specialization' },
            { key: 'licenseNumber', header: 'licenseNumber' },
            { key: 'employmentStatus', header: 'employmentStatus' },
            { key: 'hireDate', header: 'hireDate' },
            { key: 'bio', header: 'bio' },
            { key: 'isPublicProfile', header: 'isPublicProfile' },
            { key: 'departmentIds', header: 'departmentIds' },
            { key: 'departmentNames', header: 'departmentNames' },
            { key: 'primaryDepartmentId', header: 'primaryDepartmentId' },
            { key: 'primaryDepartmentName', header: 'primaryDepartmentName' },
        ],
        sample: {
            userId: '9dbd7a27-0b3c-4939-8a2f-1f20fd1ef6ee',
            staffPositionTypeId: '',
            staffPositionTypeName: 'Doctor',
            employeeCode: 'DR-001',
            specialization: 'Cardiology',
            licenseNumber: 'LIC-001',
            employmentStatus: 'ACTIVE',
            hireDate: '2026-01-15',
            bio: 'Cardiology specialist',
            isPublicProfile: 'true',
            departmentIds: '',
            departmentNames: 'Cardiology',
            primaryDepartmentId: '',
            primaryDepartmentName: 'Cardiology',
        },
    },
};
