import {
    AppointmentStatus,
    BillingStatus,
    PaymentMethod,
} from '../../../generated/prisma';
import { AppError } from '../../../shared/core/errors/app-error';
import {
    BillingLineItemData,
    BillingRepository,
    BillingStatsFilters,
    ListBillingsFilters,
} from '../domain/billing.repository';
import {
    calculateLineTotal,
    normalizeOptionalText,
    normalizeRequiredText,
    roundMoney,
} from '../domain/billing.normalizer';
import { BillingView } from '../domain/billing.entity';

const BILLING_DUE_DAYS = 14;

function addDays(date: Date, days: number) {
    const next = new Date(date);
    next.setUTCDate(next.getUTCDate() + days);
    return next;
}

function calculateSubtotal(items: BillingLineItemData[]) {
    return roundMoney(
        items.reduce((total, item) => total + item.totalPrice, 0),
    );
}

function calculateTotal(subtotal: number, taxAmount: number, discountAmount: number) {
    const total = roundMoney(subtotal + taxAmount - discountAmount);
    return total < 0 ? 0 : total;
}

function ensureMoney(value: number, fieldName: string) {
    if (!Number.isFinite(value) || value < 0) {
        throw new AppError(`${fieldName} must be a non-negative amount`, 400);
    }

    return roundMoney(value);
}

function ensurePositiveMoney(value: number, fieldName: string) {
    if (!Number.isFinite(value) || value <= 0) {
        throw new AppError(`${fieldName} must be greater than 0`, 400);
    }

    return roundMoney(value);
}

function normalizeLineItem(item: {
    serviceCatalogId?: string | null;
    inventoryItemId?: string | null;
    description: string;
    quantity: number;
    unitPrice: number;
    sourceEntityType?: string | null;
    sourceEntityId?: string | null;
}): BillingLineItemData {
    if (!Number.isFinite(item.quantity) || item.quantity <= 0) {
        throw new AppError('Quantity must be greater than 0', 400);
    }

    const unitPrice = ensureMoney(item.unitPrice, 'Unit price');
    const quantity = roundMoney(item.quantity);

    return {
        serviceCatalogId: item.serviceCatalogId ?? null,
        inventoryItemId: item.inventoryItemId ?? null,
        description: normalizeRequiredText(item.description, 'Description'),
        quantity,
        unitPrice,
        totalPrice: calculateLineTotal(quantity, unitPrice),
        sourceEntityType: normalizeOptionalText(item.sourceEntityType),
        sourceEntityId: normalizeOptionalText(item.sourceEntityId),
    };
}

function canEditBilling(billing: BillingView) {
    return (
        billing.status !== BillingStatus.PAID &&
        billing.status !== BillingStatus.CANCELLED &&
        billing.amountPaid === 0
    );
}

function hasReadablePermission(
    patientUserId: string | null,
    actorUserId: string | undefined,
    canReadAll: boolean,
) {
    return canReadAll || (patientUserId && patientUserId === actorUserId);
}

export class BillingService {
    constructor(
        private readonly billingRepository: BillingRepository,
        private readonly nowProvider: () => Date = () => new Date(),
    ) {}

    async autoGenerateFromAppointment(
        appointmentId: string,
        actorUserId?: string,
    ) {
        const existing = await this.billingRepository.findBillingByAppointmentId(
            appointmentId,
        );

        if (existing) {
            return existing;
        }

        const appointment =
            await this.billingRepository.findCompletedAppointmentForBilling(
                appointmentId,
            );

        if (!appointment) {
            throw new AppError('Appointment not found', 404);
        }

        if (appointment.status !== AppointmentStatus.COMPLETED) {
            throw new AppError('Only completed appointments can be billed', 409);
        }

        const items = await this.buildAutoGeneratedItems(appointment);
        const subtotal = calculateSubtotal(items);
        const taxAmount = 0;
        const discountAmount = 0;
        const totalAmount = calculateTotal(subtotal, taxAmount, discountAmount);
        const issuedAt = this.nowProvider();

        return this.billingRepository.createBilling({
            patientId: appointment.patientId,
            appointmentId: appointment.id,
            billingNumber: this.createBillingNumber(appointment.id, issuedAt),
            status: BillingStatus.PENDING,
            subtotal,
            taxAmount,
            discountAmount,
            totalAmount,
            dueDate: addDays(issuedAt, BILLING_DUE_DAYS),
            issuedAt,
            notes: 'Auto-generated after appointment completion',
            items,
            actorUserId,
        });
    }

    async listBillings(
        filters: ListBillingsFilters,
        actorUserId?: string,
        canReadAll = false,
    ) {
        if (filters.from && filters.to && filters.from > filters.to) {
            throw new AppError('from must be before or equal to to', 400);
        }

        const patientId = await this.resolveReadablePatientId(
            filters.patientId,
            actorUserId,
            canReadAll,
        );

        return this.billingRepository.listBillings({
            ...filters,
            patientId,
        });
    }

    async getBillingById(
        id: string,
        actorUserId?: string,
        canReadAll = false,
    ) {
        const billing = await this.getExistingBilling(id);

        if (!hasReadablePermission(billing.patient.userId, actorUserId, canReadAll)) {
            throw new AppError('Forbidden', 403);
        }

        return billing;
    }

    async updateBilling(
        id: string,
        data: {
            taxAmount?: number;
            discountAmount?: number;
            dueDate?: Date | null;
            notes?: string | null;
            items?: Array<{
                serviceCatalogId?: string | null;
                inventoryItemId?: string | null;
                description: string;
                quantity: number;
                unitPrice: number;
                sourceEntityType?: string | null;
                sourceEntityId?: string | null;
            }>;
            actorUserId?: string;
        },
    ) {
        const billing = await this.getExistingBilling(id);

        if (!canEditBilling(billing)) {
            throw new AppError(
                'Billing can only be edited before payment is recorded',
                409,
            );
        }

        const newItems = data.items?.map(normalizeLineItem) ?? [];

        if (
            data.taxAmount === undefined &&
            data.discountAmount === undefined &&
            data.dueDate === undefined &&
            data.notes === undefined &&
            newItems.length === 0
        ) {
            throw new AppError('At least one billing field is required', 400);
        }

        const subtotal = roundMoney(
            billing.subtotal + calculateSubtotal(newItems),
        );
        const taxAmount =
            data.taxAmount === undefined
                ? billing.taxAmount
                : ensureMoney(data.taxAmount, 'Tax amount');
        const discountAmount =
            data.discountAmount === undefined
                ? billing.discountAmount
                : ensureMoney(data.discountAmount, 'Discount amount');

        if (discountAmount > subtotal + taxAmount) {
            throw new AppError('Discount cannot exceed subtotal plus tax', 400);
        }

        return this.billingRepository.updateBilling(id, {
            subtotal,
            taxAmount,
            discountAmount,
            totalAmount: calculateTotal(subtotal, taxAmount, discountAmount),
            dueDate: data.dueDate,
            notes:
                data.notes === undefined
                    ? undefined
                    : normalizeOptionalText(data.notes),
            items: newItems.length > 0 ? newItems : undefined,
            actorUserId: data.actorUserId,
        });
    }

    async recordPayment(
        id: string,
        data: {
            amount: number;
            paymentMethod: PaymentMethod;
            referenceNumber?: string | null;
            notes?: string | null;
            actorUserId?: string;
        },
    ) {
        const billing = await this.getExistingBilling(id);

        if (billing.status === BillingStatus.CANCELLED) {
            throw new AppError('Cancelled billings cannot receive payments', 409);
        }

        if (billing.status === BillingStatus.PAID) {
            throw new AppError('Billing is already fully paid', 409);
        }

        if (billing.totalAmount <= 0) {
            throw new AppError('Billing has no payable balance', 409);
        }

        const amount = ensurePositiveMoney(data.amount, 'Payment amount');
        const outstanding = roundMoney(billing.totalAmount - billing.amountPaid);

        if (amount > outstanding) {
            throw new AppError('Payment amount exceeds outstanding balance', 400);
        }

        const paidAt = this.nowProvider();
        const newAmountPaid = roundMoney(billing.amountPaid + amount);
        const isPaid = newAmountPaid >= billing.totalAmount;

        return this.billingRepository.recordPayment(id, {
            amount,
            paymentMethod: data.paymentMethod,
            referenceNumber: normalizeOptionalText(data.referenceNumber),
            paidAt,
            receivedByUserId: data.actorUserId,
            notes: normalizeOptionalText(data.notes),
            newAmountPaid,
            newStatus: isPaid ? BillingStatus.PAID : BillingStatus.PARTIALLY_PAID,
            billingPaidAt: isPaid ? paidAt : null,
        });
    }

    async getBillingStats(filters: BillingStatsFilters) {
        if (filters.from && filters.to && filters.from > filters.to) {
            throw new AppError('from must be before or equal to to', 400);
        }

        return this.billingRepository.getBillingStats(filters);
    }

    private async getExistingBilling(id: string) {
        const billing = await this.billingRepository.findBillingById(id);

        if (!billing) {
            throw new AppError('Billing not found', 404);
        }

        return billing;
    }

    private async resolveReadablePatientId(
        patientId: string | undefined,
        actorUserId: string | undefined,
        canReadAll: boolean,
    ) {
        if (canReadAll) {
            return patientId;
        }

        if (!actorUserId) {
            throw new AppError('Forbidden', 403);
        }

        if (patientId) {
            const patient = await this.billingRepository.findPatientById(patientId);

            if (!patient) {
                throw new AppError('Patient not found', 404);
            }

            if (patient.userId !== actorUserId) {
                throw new AppError('Forbidden', 403);
            }

            return patientId;
        }

        const patient = await this.billingRepository.findPatientByUserId(actorUserId);
        return patient?.id ?? 'no-readable-patient';
    }

    private async buildAutoGeneratedItems(appointment: {
        id: string;
        serviceCatalogId: string;
        basePrice: number;
        service: {
            id: string;
            name: string;
            defaultPrice: number;
        };
        labOrders: Array<{
            id: string;
            items: Array<{
                id: string;
                labTest: {
                    id: string;
                    code: string;
                    name: string;
                    defaultPrice: number | null;
                };
            }>;
        }>;
        prescriptions: Array<{
            id: string;
            items: Array<{
                id: string;
                medicationName: string;
                dosage: string;
                quantityPrescribed: number;
            }>;
        }>;
    }): Promise<BillingLineItemData[]> {
        const prescriptionItems = appointment.prescriptions.flatMap(
            (prescription) => prescription.items,
        );
        const medicationPrices =
            await this.billingRepository.findMedicationCatalogPrices(
                prescriptionItems.map((item) => item.medicationName),
            );
        const priceByMedication = new Map(
            medicationPrices.map((item) => [
                item.medicationName.toLowerCase(),
                item,
            ]),
        );
        const consultationPrice = ensureMoney(
            appointment.basePrice || appointment.service.defaultPrice,
            'Consultation fee',
        );
        const items: BillingLineItemData[] = [
            normalizeLineItem({
                serviceCatalogId: appointment.serviceCatalogId,
                description: `Consultation - ${appointment.service.name}`,
                quantity: 1,
                unitPrice: consultationPrice,
                sourceEntityType: 'appointment',
                sourceEntityId: appointment.id,
            }),
        ];

        for (const labOrder of appointment.labOrders) {
            for (const item of labOrder.items) {
                items.push(
                    normalizeLineItem({
                        description: `Lab test - ${item.labTest.code} ${item.labTest.name}`,
                        quantity: 1,
                        unitPrice: item.labTest.defaultPrice ?? 0,
                        sourceEntityType: 'lab_order_item',
                        sourceEntityId: item.id,
                    }),
                );
            }
        }

        for (const item of prescriptionItems) {
            const price = priceByMedication.get(item.medicationName.toLowerCase());

            items.push(
                normalizeLineItem({
                    inventoryItemId: price?.inventoryItemId ?? null,
                    description: `Medication - ${item.medicationName} ${item.dosage}`,
                    quantity: item.quantityPrescribed,
                    unitPrice: price?.unitCost ?? 0,
                    sourceEntityType: 'prescription_item',
                    sourceEntityId: item.id,
                }),
            );
        }

        return items;
    }

    private createBillingNumber(appointmentId: string, issuedAt: Date) {
        const date = issuedAt.toISOString().slice(0, 10).replace(/-/g, '');
        return `BILL-${date}-${appointmentId.slice(0, 8).toUpperCase()}`;
    }
}
