-- This migration was created while running the seed command and duplicated the
-- initial department-service schema. Keep it as a no-op so existing migration
-- ordering remains stable without recreating tables from the first migration.
